### ISSUE TITLE
missing explanation about "src-in"

### ISSUE THREAD

**Issue by tomermes** [Phrogz/context-blender#12]
Couldn't find any online information on the blend mode called "src-in", couldn't find a matching blend mode in CS6

**Comment by Phrogz** [comment]
@tomermes The `src-in` composite mode uses the color of A and the alpha of A*B. You can see some visual examples here: https://www.w3.org/TR/SVGCompositing/#comp-op-src-in

Closing this issue, as it is not the intention of context-blender to document or describe the various blending modes.
